name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run backend tests
        run: cd apps/backend && bun run test

      - name: Run backend tests with coverage
        run: cd apps/backend && bun run test:coverage

      # カバレッジファイルの確認ステップを追加
      - name: Check coverage files
        run: |
          echo "=== Coverage directory contents ==="
          ls -la apps/backend/coverage/ || echo "No coverage directory found"
          echo ""
          echo "=== Looking for coverage files ==="
          find apps/backend -name "*coverage*.json" -o -name "*.lcov" || echo "No coverage files found"

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: apps/backend
          # ファイルが見つからない場合のエラーをスキップ
        continue-on-error: true